### ISSUE TITLE
bug on FAA()

### ISSUE THREAD

**Issue by chenm001** [huangfcn/lockfree#1]
FAA declare as **_InterlockedIncrement** on Windows and **__sync_fetch_and_add** on the Linux.
However, _InterlockedIncrement result is value after incremented, but __sync_fetch_and_add result is value before increment.
So there are must be a bug.

**Comment by huangfcn** [comment]
Although Linux will first fill & fetch the last data in the queue, the result is still correct. Thanks for pointing it out, I changed the behavior to fill & fetch from index 0 under Linux.
